apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ma43yof5t-dotnet-basic
  janus-idp.io/tekton: ma43yof5t-dotnet-basic
  backstage.io/kubernetes-id: ma43yof5t-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ma43yof5t-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
